name = "cleanui-kit-angular"
type = "webpack"
account_id = "792461088a4c863230f3faee467094b1"
# workers_dev = true
route = "angular.kitpro.cloud/*"
zone_id = "d1aaec47ec29c26199f575a683715f98"

[site]
bucket = "../dist"
entry-point = "workers-site"
